/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "name" {
  type        = string
  description = <<-EOT
      The name of the ASG.
      This value is used as the basis for naming various other resources.
      If this value is not specified a random name will be generated.
    EOT
}

variable "instance_role_policies" {
  type        = list(string)
  description = <<-EOT
    IAM Policy ARNs to attach to the instance profile.
  EOT
  default = [
    "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy",
    "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy",
    "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
    "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess",
    "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
  ]
}

variable "ami_id" {
  type        = string
  description = <<-EOT
    AMI ID for instances created by the ASG.
    Conflicts with `ami_ssm_parameter`.
  EOT
  default     = null
}

variable "ami_ssm_parameter" {
  type        = string
  description = <<-EOT
    Name of SSM parameter that contains the AMI ID to use.
    ex. "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended"
    Conflicts with `ami_id`.
  EOT
  default     = null
}

variable "instance_type" {
  type        = string
  description = <<-EOT
    Instance type
  EOT
  default     = "t2.micro"
}

variable "user_data" {
  type        = string
  description = <<-EOT
    Instance User Data.
    See: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html
  EOT
  default     = null
}

variable "security_group_ids" {
  type        = list(string)
  description = <<-EOT
    Security groups to attach to the managed instances.
  EOT
  default     = null
}

variable "aws_packages" {
  type        = list(string)
  description = <<-EOT
    List of AWS packages to deploy via SSM.
  EOT
  default = [
    "AWSCodeDeployAgent",
    "AmazonCloudWatchAgent"
  ]
}

variable "target_group_arns" {
  type        = list(string)
  description = <<-EOT
    Load balancer targets to register with.
  EOT
  default     = null
}

variable "subnet_ids" {
  type        = list(string)
  description = <<-EOT
    Subnets to deploy instances in.
  EOT
}

variable "min_size" {
  type        = number
  description = <<-EOT
    Minimum number of instances to create.
  EOT
  default     = 1
}

variable "max_size" {
  type        = number
  description = <<-EOT
    Maximum number of instances to create.
  EOT
  default     = 1
}

variable "cloudwatch_config" {
  type        = string
  description = <<-EOT
    Cloudwatch config file contents.
  EOT
  default     = null
}

variable "root_volume_size" {
  type        = number
  description = <<-EOT
    Size in GB of root volume size.
  EOT
  default     = 100
}

variable "instance_tags" {
  type        = map(string)
  description = <<-EOT
    Tags to apply to instances.
    Use the provider `default_tags` feature for more consistent tagging.
  EOT
  default     = {}
}
