/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "availability_zones" {
  type        = list(string)
  description = <<-EOT
    Availability zones to create resources in.
  EOT
}

variable "cidr" {
  type        = string
  description = <<-EOT
    CIDR block for VPC
  EOT
}

variable "private_subnets" {
  type        = list(string)
  description = <<-EOT
      List of CIDR blocks for private access subnets.
  EOT
  default     = []
}

variable "public_subnets" {
  type        = list(string)
  description = <<-EOT
      List of CIDR blocks for public access subnets.
  EOT
  default     = []
}
