/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "result" {
  description = <<-EOT
      The result of the module.
    EOT
  value = {
    aws_lb         = aws_lb.this
    http_listener  = aws_lb_listener.this
    https_listener = aws_lb_listener.https
    route53_record = data.aws_route53_zone.this
  }
}
