/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "availability_zones" {
  type        = list(string)
  description = <<-EOT
    Availability zones to create resources in.
  EOT
}

variable "vpc_cidr" {
  type        = string
  description = <<-EOT
    CIDR block for VPC
  EOT
}

variable "vpc_name" {
  type        = string
  description = <<-EOT
    Name of the VPC.
  EOT
}

variable "subnets_netmask_length" {
  type        = number
  description = <<-EOT
    Number of subnet bits for subnets.
  EOT
}

variable "client_cidrs" {
  type        = list(string)
  description = <<-EOT
    Client CIDR blocks to route.
  EOT
}
