/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "result" {
  description = <<-EOT
      The result of the module.
  EOT
  value = {
    task_definition    = aws_ecs_task_definition.this
    service            = aws_ecs_service.this
    target_group       = aws_lb_target_group.this
    listener_rule      = aws_lb_listener_rule.this
    ecs_execution_role = aws_iam_role.ecs_execution
  }
}
