/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "result" {
  description = <<-EOT
      The result of the module.
  EOT
  value = {
    ipam = aws_vpc_ipam.this
    pool = aws_vpc_ipam_pool.this
    cidr = aws_vpc_ipam_pool_cidr.this
  }
}
