/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "root_cidr" {
  type        = string
  description = <<-EOT
    Top level CIDR.
  EOT
}

variable "ipam_regions" {
  type        = list(string)
  description = <<-EOT
    List of regions to enable the IPAM in.  The region of the provider is
    automatically included.
  EOT
  default     = []
}
