/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "input" {
  type        = string
  description = <<-EOT
      This variable is not used.
    EOT
  default     = null
}
