/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "result" {
  description = <<-EOT
      The result of the module.
  EOT
  value = {
    cluster           = aws_ecs_cluster.this
    capacity_provider = aws_ecs_capacity_provider.this
  }
}
