/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "name" {
  type        = string
  description = <<-EOT
    Name of ECS Cluster and other resources.
  EOT
}

variable "autoscaling_group_arn" {
  type        = string
  description = <<-EOT
    ARN of autoscaling group to associate with the cluster.
  EOT
}
