/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "result" {
  description = <<-EOT
      The result of the module.
  EOT
  value = {
    vpc        = module.vpc.result
    asg        = module.asg.result
    alb        = module.alb.result
    ecs        = module.ecs.result
    log_bucket = module.log_bucket.result
  }
}
